services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    env_file:
      - ./client/.env
